services:
  app:
    container_name: nextjs-app
    build:
      context: https://github.com/KauTryKauCuba/0001.git#main
      dockerfile: Dockerfile
      # This line fixes the DNS/internet issue during build
      network: host
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
